name: 'Test upgrade Wazuh agent package on allocator'
description: 'Test upgrade Wazuh agent package on allocator'

inputs:
  old_package_url:
    description: 'Package url to update from'
    required: true
  expected_upgrade_version:
    description: 'Expected package version after upgrading'
    required: true
  tested_docker:
    description: 'image:tag of tested Docker'
    required: true
  architecture:
    description: 'Architecture of the testing container, only required if it is ppc64'
    required: false 

runs:
  using: 'composite'
  steps:
    - name: Run test upgrade Wazuh agent package
      shell: bash
      run: |
        if [ "${{ inputs.architecture }}" == "ppc64" ]; then
          ${{ env.SSH_COMMAND }} 'docker create --name test_container --entrypoint '/bin/bash' ${{ inputs.tested_docker }} \
            -c "/tests/smoke_upgrade_test.sh ${{ inputs.old_package_url }} ${{ inputs.expected_upgrade_version }}"'
          ${{ env.SSH_COMMAND }} 'docker cp $(pwd)/wazuh/.github/actions/4_builderpackage_linux-smoke-upgrade-test/. test_container:/tests/'
          ${{ env.SSH_COMMAND }} 'docker cp /tmp/. test_container:/packages'
          ${{ env.SSH_COMMAND }} 'docker start test_container'
          ${{ env.SSH_COMMAND }} 'docker wait test_container'
          ${{ env.SSH_COMMAND }} 'docker cp test_container:/packages/upgraded_version.log /tmp/upgraded_version.log'
          ${{ env.SSH_COMMAND }} 'docker rm test_container'
        else
          ${{ env.SSH_COMMAND }} 'sudo docker run \
            -v $(pwd)/wazuh/.github/actions/4_builderpackage_linux-smoke-upgrade-test/:/tests \
            -v /tmp/:/packages \
            --entrypoint '/bin/bash' ${{ inputs.tested_docker }} \
            -c "/tests/smoke_upgrade_test.sh ${{ inputs.old_package_url }} ${{ inputs.expected_upgrade_version }}"'
        fi
