name: Inventory Harvester Tests

on:
  workflow_dispatch:
  pull_request:
  # Pull request events
    types: [synchronize, opened, reopened, ready_for_review]
  # Path filtering
    paths:
      - ".github/workflows/inventory-harvester-tests.yml"
      - ".github/actions/compile_and_test/action.yml"
      - ".github/actions/clang_format/action.yml"
      - ".github/actions/doxygen/action.yml"
      - ".github/actions/vulnerability_scanner_deps/action.yml"
      - "src/shared_modules/router/**"
      - "src/shared_modules/indexer_connector/**"
      - "src/wazuh_modules/http-request/**"
      - "src/shared_modules/utils/**"

jobs:
  style-and-documentation:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Inventory harvester - Coding style
        uses: ./.github/actions/clang_format
        with:
          path: src/wazuh_modules/inventory_harvester
          id: inventory_harvester

      - name: Inventory harvester - Doxygen
        uses: ./.github/actions/doxygen
        with:
          path: src/wazuh_modules/inventory_harvester
          id: inventory_harvester

  inventory-harvester-modules:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Project dependencies
        uses: ./.github/actions/vulnerability_scanner_deps

      ########################
      # Compilation and test #
      ########################

      # Router
      - name: Router - Compilation
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/router
          test: "false"

      # Indexer connector
      - name: Indexer connector - Compilation
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/indexer_connector
          test: "false"

      # Utils
      - name: Utils - Compilation
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/utils
          flags: "-DTARGET=server"
          test: "false"

      # Inventory harvester
      - name: Inventory harvester - Compilation and test
        uses: ./.github/actions/compile_and_test
        with:
          path: src/wazuh_modules/inventory_harvester

      - name: Inventory harvester - Coverage
        uses: ./.github/actions/coverage
        with:
          path: src/wazuh_modules/inventory_harvester
          id: inventory_harvester


  inventory-harvester-asan:
    strategy:
      matrix:
        os: [ ubuntu-24.04, ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Project dependencies
        uses: ./.github/actions/vulnerability_scanner_deps

      ########################
      # Compilation and test #
      ########################

      # Router
      - name: Router - Compilation and test
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/router
          test: "false"
          asan: "true"

      # Indexer connector
      - name: Indexer connector - Compilation and test
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/indexer_connector
          test: "false"
          asan: "true"

      # Utils
      - name: Utils - Compilation and test
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/utils
          flags: "-DTARGET=server"
          test: "false"
          asan: "true"

      # Inventory harvester
      - name: Inventory harvester - Compilation and test
        uses: ./.github/actions/compile_and_test
        with:
          path: src/wazuh_modules/inventory_harvester
          asan: "true"

      - name: Inventory harvester - Test tool
        run: |
          INVENTORY_HARVESTER_PATH=$(pwd)/src/wazuh_modules/inventory_harvester
          cd src/wazuh_modules/inventory_harvester/build/testtool
          echo "{}" > states_update_mappings.json
          ./inventory_harvester_testtool -c $INVENTORY_HARVESTER_PATH/testtool/config.json -t $INVENTORY_HARVESTER_PATH/testtool/template.json -i $INVENTORY_HARVESTER_PATH/testtool/inputs/


  inventory-harvester-qa:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Project dependencies
        uses: ./.github/actions/vulnerability_scanner_deps

      # Router
      - name: Router - Compilation and test
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/router
          test: "false"

      # Indexer connector
      - name: Indexer connector - Compilation and test
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/indexer_connector
          test: "false"

      # Utils
      - name: Utils - Compilation and test
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/utils
          flags: "-DTARGET=server"
          test: "false"

      # Inventory harvester
      - name: Inventory harvester - Compilation and test
        uses: ./.github/actions/compile_and_test
        with:
          path: src/wazuh_modules/inventory_harvester
          test: "false"

      # Install python dependencies
      - name: Install dependencies
        run: |
          pip install -r src/wazuh_modules/inventory_harvester/qa/requirements.txt

      - name: Run tests
        env:
          REPORT_OUTPUT: report.md
        run: |
          cd src
          echo "REPORT_FILE=${{ env.REPORT_OUTPUT }}" >> "$GITHUB_ENV"
          echo "{}" > states_update_mappings.json
          python -m pytest -rA --html=report.html --self-contained-html --md-report --md-report-verbose=1 --md-report-zeros empty --md-report-color never --md-report-output "$REPORT_OUTPUT" -vv wazuh_modules/inventory_harvester/qa/ --log-cli-level=DEBUG

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: inventory-harvester-qa-logs
          path: src/log_*.out

      - name: Output reports to the job summary
        if: always()
        shell: bash
        run: |
          cd src
          cat "$REPORT_FILE" >> $GITHUB_STEP_SUMMARY

      - name: Upload HTML report
        if: always()
        env:
          REPORT_FILENAME: report.html
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.REPORT_FILENAME }}
          path: src/${{ env.REPORT_FILENAME }}
